services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Sebkln\ContentSlug\:
    resource: '../Classes/*'
    exclude: '../Classes/{Evaluation,FormEngine}'
  Sebkln\ContentSlug\Listener\ModifyFragment:
    tags:
      - name: event.listener
        identifier: 'content-slug/frontend/modify-fragment'
